spring:
    datasource:
        url: jdbc:mysql://localhost:3306/activity-tracker?createDatabaseIfNotExist=true
        username: root
        password: root
    jpa:
        hibernate.ddl-auto: none
        generate-ddl: true
        show-sql: false

jira:
    user:
        email: drago.mazic.2853@gmail.com
        pass: kEpqHiGXTe2HFKky3yAk9520
    team:
        url: https://team-16684562158657.atlassian.net/


emailPassword: drago.mazic.2853@gmail.com:kEpqHiGXTe2HFKky3yAk9520
secret: test
tokenExpirationDay: 2
