spring:
    datasource:
        url: jdbc:mysql://localhost:3306/activity-tracker?createDatabaseIfNotExist=true
        username: root
        password: root
    jpa:
        hibernate.ddl-auto: none
        generate-ddl: true
        show-sql: false

secret: test
tokenExpirationDay: 2
