spring:
    data:
        mongodb:
            uri: mongodb://localhost:27017/report
            database: report

        arangodb:
            host: localhost
            port: 8529
            database: _system
            user: root
            password: root
    datasource:
        url: jdbc:mysql://localhost:3306/activity-tracker?createDatabaseIfNotExist=true
        username: root
        password: root
    jpa:
        hibernate.ddl-auto: none
        generate-ddl: true
        show-sql: false
    config:
        import: optional:secrets.yaml

secret: test
tokenExpirationDay: 2

ms:
    cors:
        origins: "*"

# ArangoDB configuration
arangodb:
    hosts: localhost
    port: 8529
    user: root
    password: root
